services:
  yttri:
    restart: always
    build: .
    container_name: yttri-yttri-1
    ports:
      - 5003:80
    volumes:
      - ./:/code
      - /tank/sqlite/yttri/dbs:/code/dbs
      - /tank/sqlite/yttri/k1_dbs:/code/k1_dbs


